apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth
  name: auth
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: auth
status:
  loadBalancer: {}
