apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devices
  name: devices
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app: devices
status:
  loadBalancer: {}
